[project]
name = "my-app"
version = "0.1.0"
description = "This project is created by uv, we use it to test uv"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "notebook>=7.5.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "ruff>=0.14.6",
]
